  // File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTh7_Dj22D2hAQH6eH0ouXL6RHb0fW-gE',
    appId: '1:677305770843:web:7ad3c3c910df43318ab07e',
    messagingSenderId: '677305770843',
    projectId: 'fir-app-9be59',
    authDomain: 'fir-app-9be59.firebaseapp.com',
    storageBucket: 'fir-app-9be59.appspot.com',
    measurementId: 'G-ZCDWSPXHNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxPuAI0OBQZlCYyvnGLfnxV8lP1L4_tek',
    appId: '1:677305770843:android:34b7b05e87fd9ab18ab07e',
    messagingSenderId: '677305770843',
    projectId: 'fir-app-9be59',
    storageBucket: 'fir-app-9be59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZzlHJRCiGzNNJlCOAlE7LGmdRdGMWe3Q',
    appId: '1:677305770843:ios:c4ed226bd98c4db58ab07e',
    messagingSenderId: '677305770843',
    projectId: 'fir-app-9be59',
    storageBucket: 'fir-app-9be59.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZzlHJRCiGzNNJlCOAlE7LGmdRdGMWe3Q',
    appId: '1:677305770843:ios:10f10f6295f263be8ab07e',
    messagingSenderId: '677305770843',
    projectId: 'fir-app-9be59',
    storageBucket: 'fir-app-9be59.appspot.com',
    iosBundleId: 'com.example.demoApp.RunnerTests',
  );
}
